// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3G5x-G9pwxwGEhsjJ2Ye2y_cpXiNygWc',
    appId: '1:588869383950:web:18046071bfed0e0e8bc95f',
    messagingSenderId: '588869383950',
    projectId: 'systemcafe-852b7',
    authDomain: 'systemcafe-852b7.firebaseapp.com',
    storageBucket: 'systemcafe-852b7.firebasestorage.app',
    measurementId: 'G-QR7WQCFLER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOCaiqXki0K7fLbBikXT5VU0_MRC09pX0',
    appId: '1:588869383950:android:75c3014eb904b0b18bc95f',
    messagingSenderId: '588869383950',
    projectId: 'systemcafe-852b7',
    storageBucket: 'systemcafe-852b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwmzhUgMYuOVPO7NTEEPh8xNyFbQb6FBc',
    appId: '1:588869383950:ios:731a5a34a9de23d18bc95f',
    messagingSenderId: '588869383950',
    projectId: 'systemcafe-852b7',
    storageBucket: 'systemcafe-852b7.firebasestorage.app',
    iosBundleId: 'com.example.floracafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwmzhUgMYuOVPO7NTEEPh8xNyFbQb6FBc',
    appId: '1:588869383950:ios:731a5a34a9de23d18bc95f',
    messagingSenderId: '588869383950',
    projectId: 'systemcafe-852b7',
    storageBucket: 'systemcafe-852b7.firebasestorage.app',
    iosBundleId: 'com.example.floracafe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3G5x-G9pwxwGEhsjJ2Ye2y_cpXiNygWc',
    appId: '1:588869383950:web:e5d806aa8e1d15888bc95f',
    messagingSenderId: '588869383950',
    projectId: 'systemcafe-852b7',
    authDomain: 'systemcafe-852b7.firebaseapp.com',
    storageBucket: 'systemcafe-852b7.firebasestorage.app',
    measurementId: 'G-YF45L1X6DT',
  );
}
